version: '3.7'
services:
  consul:
    image: hashicorp/consul:1.15
    container_name: aws-consul
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: agent -server -bootstrap -ui -client=0.0.0.0